### ISSUE TITLE
Dockerfiles are hard to manage

### ISSUE THREAD

**Issue by umutoztunc** [WinMin/ctfpwn-env#12]
I think dockerfiles are containing lots of repetitive lines. It makes managing them frustrating. For example, if we are going to add a tool to all dockers, we need to literally edit all dockerfiles. If we are planning to support more ubuntu versions (especially non-lts ones), it will be harder. 

One possible solution to this problem is generating files with a script. In this script, we can put common things to one list and use other containers to extend each specific image if they have uncommon things.

It would be nice if dockerfile had import/include kind of things so that we could create a common file to include. It is not officially supported, but I've found this [dockerfile-plus](https://github.com/edrevo/dockerfile-plus) project. The project kind of looks young and immature to me yet. Thus, I am not sure if we should use it or not, but it is worth having an eye on it.

**Comment by winmin** [comment]
Now we're using a single Dockerfile
