### ISSUE TITLE
None of the images has sudo command

### ISSUE THREAD

**Issue by umutoztunc** [WinMin/ctfpwn-env#2]
Even though we are root and we do not need `sudo` command. Some installation scripts have sudo in it like [this](https://github.com/ChrisTheCoolHut/PinCTF/blob/master/installPin.sh).

If `sudo` is not installed the commands that start with sudo in scripts will fail. Thus, it is better to have it installed.

**Comment by WinMin** [comment]
Fixes #878c1709239feef4d5fbd06fa5c49eb096a1920a

**Comment by winmin** [comment]
fix: 7b37e212b7e66b91142084e20eee1aea044a48b6
